### ISSUE TITLE
Handle invalid message.payload types

### ISSUE THREAD

**Issue by jthomas** [node-red/node-red-bluemix-nodes#11]
Sending the QA node a non-string message.payload causes the application to crash. We should handle this error state without dying.

```
2015-04-22T11:27:08.07+0200 [App/0]      OUT 22 Apr 09:27:08 - [error] [watson-question-answer:e3c97ae0.1c3688] API responses with error: [object Object]
2015-04-22T11:27:08.08+0200 [App/0]      OUT 22 Apr 09:27:08 - [red] Uncaught Exception:
2015-04-22T11:27:08.08+0200 [App/0]      OUT 22 Apr 09:27:08 - TypeError: Cannot read property '0' of null
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at /home/vcap/app/node_modules/node-red-bluemix-nodes/watson/qa.js:58:33
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at Request._callback (/home/vcap/app/node_modules/node-red-bluemix-nodes/node_modules/watson-developer-cloud/lib/requestwrapper.js:68:5)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at Request.self.callback (/home/vcap/app/node_modules/node-red-bluemix-nodes/node_modules/watson-developer-cloud/node_modules/request/request.js:360:22)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at Request.emit (events.js:98:17)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at Request.<anonymous> (/home/vcap/app/node_modules/node-red-bluemix-nodes/node_modules/watson-developer-cloud/node_modules/request/request.js:1202:14)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at Request.emit (events.js:117:20)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/node-red-bluemix-nodes/node_modules/watson-developer-cloud/node_modules/request/request.js:1150:12)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at IncomingMessage.emit (events.js:117:20)
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at _stream_readable.js:944:16
2015-04-22T11:27:08.08+0200 [App/0]      OUT     at process._tickCallback (node.js:448:13)
```

**Comment by knolleary** [comment]
It could be argued that if you are providing `question_and_answer_healthcare.ask`  with a callback for errors, it shouldn't be throwing an exception for us to catch as well..

**Comment by knolleary** [comment]
Ah ignore that - it is doing the right thing - we log the error, but then continue trying to process the response regardless.
